--http://www.juliandyke.com/Research/Database/IdentityColumns.php
--http://www.oraclebuffer.com/oracle-internals/oracle-database-12c-new-feature-identity-column-or-auto-increment-column/
-- delete the user and post tables  
--DROP TABLE BHPOST;
--DROP TABLE BHUSER;

--------------------------------------------------------
--  DDL for Table BHUSER
--------------------------------------------------------
  CREATE TABLE BHUSER 
   ("BHUSERID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE , 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL, 
	"USERPASSWORD" VARCHAR2(50 BYTE), 
	"MOTTO" VARCHAR2(100 BYTE) NOT NULL, 
	"USEREMAIL" VARCHAR2(100 BYTE) NOT NULL, 
	"JOINDATE" DATE NOT NULL,
	 PRIMARY KEY ("BHUSERID")
   ) ;
--------------------------------------------------------
--  DDL for Table BHPOST
--------------------------------------------------------

 CREATE TABLE BHPOST 
   ("POSTID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ,  
	"POSTDATE" DATE NOT NULL, 
	"POSTTEXT" VARCHAR2(141 BYTE) NOT NULL, 
	"BHUSERID" NUMBER NOT NULL,
	 PRIMARY KEY ("POSTID")
   );

--------------------------------------------------------
--  Test data for Table BHUSER
--------------------------------------------------------
Insert into BHUSER (USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE) values ('user 1','password','motto for user 1','user1@domain.com',to_date('18-JUN-16','DD-MON-RR'));
Insert into BHUSER (USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE) values ('user 2','password','motto for user 2','user2@domain.com',to_date('22-JUL-15','DD-MON-RR'));
Insert into BHUSER (USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE) values ('user 3','password','motto for user 3','user3@domain.com',to_date('31-DEC-16','DD-MON-RR'));
Insert into BHUSER (USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE) values ('user 4','password','motto for user 4','user4@domain.com',to_date('22-JAN-17','DD-MON-RR'));

-- commit saves the data to the database
commit;

--------------------------------------------------------
--  Test data for Table BHPOST
--------------------------------------------------------
Insert into BHPOST (POSTDATE,POSTTEXT,BHUSERID) values (to_date('18-JUN-17','DD-MON-RR'),'This is a test post',1);
Insert into BHPOST (POSTDATE,POSTTEXT,BHUSERID) values (to_date('21-AUG-17','DD-MON-RR'),'Bullhorn is a fun program!',2);
Insert into BHPOST (POSTDATE,POSTTEXT,BHUSERID) values (to_date('30-JUL-17','DD-MON-RR'),'Hello, I am posting something',2);
-- commit saves the data to the database
commit;

-- view the data from your tables
select * from bhuser;
select * from bhpost;

